### ISSUE TITLE
minor syntax highlighting errors in routes

### ISSUE THREAD

**Issue by wolftune** [alx741/yesod.vim#1]
in routes file:

* route itself loses highlighting if it has a hyphen, as in `/test-page` where `-page` won't be highlighted
* arg loses highlighting if it happens to have a name with a capital R in the camelCase as in `colorRed` (where the `ed` is unhighlighted)
    * I'm guessing it just stops after the R thinking it's the "resource" signifier, when it should ideally only stop at a capital R if it's followed by a space

**Comment by alx741** [comment]
Thanks a lot for your report
