### ISSUE TITLE
jump to handler broken if name has a letter r

### ISSUE THREAD

**Issue by wolftune** [alx741/yesod.vim#2]
e.g. `SearchR` gives error "The handler file for SeaR does not exist"

It's possible this is an error message error rather than a jump error. I get the same error with the correct text for other routes that have no `r` in the name. My project has handlers within website/src/Handler/ subdirectory, so maybe this is failing to go to that since it isn't the normal location in Yesod scaffolding. If so, that's a separate additional issue to address.

**Comment by alx741** [comment]
Thank you for reporting. I've fixed the problem with routes that contains an `r` , it was actually a deeper problem, but with an easy fix fortunately.

About the handlers in a non-standard location, I'll add a configuration variable for that specific case. Will document that in the README file as well.
