### ISSUE TITLE
list of locations for handler location?

### ISSUE THREAD

**Issue by wolftune** [alx741/yesod.vim#4]
It was pointed out that making the location "src/" and such could break normal Yesod scaffolded projects. So, (A) is that right? and (B) can it be a list or something so that vim-yesod will work with multiple projects that may have Handlers in different places?

**Comment by alx741** [comment]
Yesod gives you the flexibility to craft the file structure you need, I don't think there is evidence to backup that using `src/` for the handlers may *break* the scaffolding, maybe it will require some Juggling but it can be done so the compilation and devel server will work just fine.

The problem with that though is Yesod tools getting confused. *yesod-bin* for instance expects the `Application.hs`, `Foundation.hs`, `Settings.hs`, `Model.hs` and `Import.hs` files to be in the root directory of the project, along side the `.cabal` file.

And yes, with the `g:yesod_handlers_path` you can set the directory where the handlers are kept (it will be searched recursively). This is of course globally, so when you switch to a Yesod project that sticks to the standard scaffolding tree you'll have a bit of a problem...

For that cases you can use [vim-projectionist](https://github.com/tpope/vim-projectionist) so you can have a different `g:yesod_handlers_path` based on the project you're currently in. But given that this might be a relatively common use case, I'll try to make it a list of paths as you suggested

**Comment by alx741** [comment]
Ok, the `g:yesod_handlers_path` variable was removed, so now:

```vim
let g:yesod_handlers_directories = ['Handler', 'src']
```

Should do it for your particular case

**Comment by wolftune** [comment]
indeed, it's working for my case, and I verified with another yesod project that it works for that too, yay!

**Comment by alx741** [comment]
perfect!, I think the i18n messages directory will need this kind of list as well, just in case....
